### ISSUE TITLE
Problem with Java Runtime (class file version)

### ISSUE THREAD

**Issue by evandroabukamel** [xcporter/MetaView#2]
Hello, this is a great project, it saves a lot of documentation time. But after I upgraded my Kotlin to 1.5 I have the following error:

```
> Task :generateUmlDiagrams FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateUmlDiagrams'.
> com/xcporter/KotlinLexer has been compiled by a more recent version of the Java Runtime 
(class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

I'm quite new to Kotlin, so I don't know what this error means.
What can e do to solve it?

Thanks.

**Comment by xcporter** [comment]
It looks like you're using a Java 11 runtime, and I compiled this version targeting Java 14. 
One solution would be to make sure that Gradle is using a runtime of 14 or higher. 

This can be done either by resetting your JAVA_HOME environmental variable to a newer JDK, 
or if you're using intellij, you can pick which JDK to use for Gradle in preferences. 

I'll see about adding further backwards compatibility, since Java 11 is still is wide use.

**Comment by evandroabukamel** [comment]
I tried it but didn't work. I'm using SDKMAN to switch between versions. Got a different error this time.

```
$ sdk use java 15.0.1-zulu 
$ ./gradlew deteckMain

> Task :detektMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':detektMain'.
> 'org.jetbrains.kotlin.analyzer.AnalysisResult org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(org.jetbrains.kotlin.com.intellij.openapi.project.Project, java.util.Collection, org.jetbrains.kotlin.resolve.BindingTrace, org.jetbrains.kotlin.config.CompilerConfiguration, kotlin.jvm.functions.Function1, kotlin.jvm.functions.Function2, org.jetbrains.kotlin.com.intellij.psi.search.GlobalSearchScope, java.util.List, int, java.lang.Object)'

```

**Comment by xcporter** [comment]
That's from the Detekt plugin, so I don't really know what might be going on there. The metaview task would be called`generateUmlDiagrams`

**Comment by xcporter** [comment]
It's not properly tagged, but Java 11 is now supported in version 0.0.6
